# Minimal assets-only configuration
name = "qasasforkids"
compatibility_date = "2025-09-04"

[assets]
directory = "dist"

[env.production]
workers_dev = false
[[env.production.routes]]
pattern = "qasasforkids.com/*"
zone_name = "qasasforkids.com"
[[env.production.routes]]
pattern = "www.qasasforkids.com/*"
zone_name = "qasasforkids.com"

[env.dev]
name = "qasasforkids-dev"
workers_dev = true
